### PR TITLE
Add commands for managing Git repositories

### PR DESCRIPTION
**Pull request by AnnikaCodes**
I don't see a way to test this without adding a Discord key; I tried to get it log in on an unregged account and I just get `Login failed: [object Object]` which isn't too helpful. Do you have unit tests?

### CODE REVIEW

**Comment by CarimA** [comment]
Hi Annika,

For logging in, there are a bunch of defined environmental variables which can be set at a system level or inside a text file `.env` at the root folder, at the moment, just lacking in any documentation mentioning what they are or what they do.

```
PORT - Port for the webserver to use
PSIM_USERNAME - Pokemon Showdown account username
PSIM_PASSWORD - Pokemon Showdown account password
PSIM_AVATAR - Pokemon Showdown avatar
PSIM_AUTO_JOIN_ROOMS - Comma separated list of rooms to join when logged in to Pokemon Showdown
PSIM_TOUR_ROOM - Room where scheduled tournaments will be created
DISCORD_TOKEN - Login token for Discord bot
DISCORD_SERVER_ID - Server ID for which server tournament messages will be posted in (going to rename at some point to be more descriptive)
DISCORD_ANNOUNCE_CHANNEL - Channel ID for where announcements are read from and relayed the PS room defined at PSIM_TOUR_ROOM
DISCORD_TOURS_CHANNEL - Channel ID where tournament voting/starting announcements are posted
```

No unit tests, the code was very much created in a fast-and-loose-get-it-working-now manner, there are a number of things I'd like to reafactor (particularly in tournaments module) down the line.

**Comment by AnnikaCodes** [comment]
I set `PSIM_USERNAME` to an unregged account and still got the `[object Object]` error

**Comment by CarimA** [comment]
That's likely an issue with TsPsimClient (https://github.com/CarimA/TsPsimClient), thinking about it, I never did actually handle unregistered accounts 😅 

For now, just test it with a registered acc, and I'll add that to my todo list with TsPsimClient (and get around to start adding some defensive guards around more problem areas...)

**Comment by AnnikaCodes** [comment]
I don't think I can request reviews here but it's tested and seems to work.

**Pull request merged**
